### ISSUE TITLE
Problem with unicode text

### ISSUE THREAD

**Issue by gino4nx** [wouterken/htmltoadf#12]
Having problem with unicode text.
for example converting Georgian text: გამარჯობა, როგორ ხარ? its converted like ????????, ????? ???? 
I'm using on .Net

**Comment by wouterken** [comment]
Hi @gino4nx 
Are you using FFI to invoke the library?

I believe you'll need to let it know that the encoding of the returned string is UTF-8.
E.g. see: UnmanagedType.LPUTF8Str in https://learn.microsoft.com/en-us/dotnet/framework/interop/default-marshalling-for-strings#strings-used-in-platform-invoke.

You can see similar behaviour in the below Ruby example:

## Default encoding (ASCII-8BIT)
```ruby
irb(main):020> puts HTMLToADF.convert("<h1>გამარჯობა, როგორ ხარ?</h1>")
(irb):20:in `write': "\xE1" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)
	from (irb):20:in `puts'
	from (irb):20:in `puts'
	from (irb):20:in `<main>'
	from <internal:kernel>:187:in `loop'
	from /Users/pico/.rbenv/versions/3.3.0/lib/ruby/gems/3.3.0/gems/irb-1.11.1/exe/irb:9:in `<top (required)>'
	from /Users/pico/.rbenv/versions/3.3.0/bin/irb:25:in `load'
	from /Users/pico/.rbenv/versions/3.3.0/bin/irb:25:in `<main>'
```

## UTF-8
```
irb(main):021> puts HTMLToADF.convert("<h1>გამარჯობა, როგორ ხარ?</h1>").force_encoding("utf-8")
{"version":1,"type":"doc","content":[{"type":"heading","attrs":{"level":1},"content":[{"type":"text","text":"გამარჯობა, როგორ ხარ?"}]}]}
=> nil
```

```ruby
```
