### ISSUE TITLE
Line breaks not getting added

### ISSUE THREAD

**Issue by arochelle12** [wouterken/htmltoadf#13]
When I paste my html into the GUI version at https://wouterken.github.io/htmltoadf/ my html is translated correctly with the line breaks being translated into {
               "type": "hardBreak"
            }
but when I use the same html in the docker container these are left out.

**Comment by wouterken** [comment]
Hey @arochelle12 
Can you please provide a minimal reproducible example, with input, current output and expected output?
E.g.
```bash
❯ echo "<p>Demonstrate</br>line break problem</p>" | docker run --rm -i wouterken/html2adf:0.1.10 | jq
{
  "version": 1,
  "type": "doc",
  "content": [
    {
      "type": "paragraph",
      "content": [
        {
          "type": "text",
          "text": "Demonstrate"
        },
        {
          "type": "hardBreak"
        },
        {
          "type": "text",
          "text": "line break problem"
        }
      ]
    }
  ]
}
```

Expected output
```
{ 
   ...something else..
}
```

**Comment by arochelle12** [comment]
Using your example, this is the output I get when I run the same thing:

```
$ echo "<p>Demonstrate</br>line break problem</p>" | docker run --rm -i wouterken/html2adf:latest | jq
{
  "version": 1,
  "type": "doc",
  "content": [
    {
      "type": "paragraph",
      "content": [
        {
          "type": "text",
          "text": "Demonstrate"
        },
        {
          "type": "text",
          "text": "line break problem"
        }
      ]
    }
  ]
}
```

My expected output is what you have in your example.

**Comment by wouterken** [comment]
Hey @arochelle12 

Thanks for the example, that was helpful. It seems I've simply neglected to bump the `latest` tag on the image on Dockerhub (note your use of `latest` vs `0.1.10` in my example). I've bumped latest to be inline with 0.1.10.
If you try again now, you _should_ see the expected results.
