### ISSUE TITLE
`<br>` tag is not translated properly

### ISSUE THREAD

**Issue by flyinbutrs** [wouterken/htmltoadf#4]
# Input
```html
<p>text<br/>on two lines</p>
```
Rendered:
![image](https://github.com/wouterken/htmltoadf/assets/1248221/b850774c-ecaf-42be-84d9-4e2a8a4adc7e)

# Output
```json
{
   "version": 1,
   "type": "doc",
   "content": [
      {
         "type": "paragraph",
         "content": [
            {
               "type": "text",
               "text": "text"
            },
            {
               "type": "text",
               "text": "on two lines"
            }
         ]
      }
   ]
}
```

Rendered:

![image](https://github.com/wouterken/htmltoadf/assets/1248221/2dad0a56-3aac-44d8-96fb-4252e43c9d56)

# Expected Output
```json
{
   "version": 1,
   "type": "doc",
   "content": [
      {
         "type": "paragraph",
         "content": [
            {
               "type": "text",
               "text": "text"
            },
            {
               "type": "hardBreak"
            },
            {
               "type": "text",
               "text": "on two lines"
            }
         ]
      }
   ]
}
```

Rendered:
![image](https://github.com/wouterken/htmltoadf/assets/1248221/f55ea36b-87a8-41e8-809e-bd9af65143b8)

~~I expect this is a bit of leaky abstraction issue because ADF is weird, but I think treating <br> as paragraph separator is necessary.~~

**Comment by flyinbutrs** [comment]
Slight update here, in some unrelated research, I found a better solution than abusing the `paragraph` type. Instead, you want to insert the type `hardbreak`. 

I've updated the `Expected Output` section above.

https://developer.atlassian.com/cloud/jira/platform/apis/document/nodes/hardBreak/

**Comment by wouterken** [comment]
Thanks for the tip @flyinbutrs . I have updated the version 0.1.8 to translate <br/>'s to hardBreaks as suggested.
