### ISSUE TITLE
Feedback on the web version of the library

### ISSUE THREAD

**Issue by ecostanzi** [wouterken/htmltoadf#8]
Hi @wouterken, 

I've developed a simple rocket web app that wraps the converter in a web API: https://github.com/ecostanzi/html2adf-api/blob/main/src/main.rs 

Since I've never developed anything with rust I'm interested in having feedback about it. Let me know if you see any problems or improvements in my implementation.

Thank you for your work!

**Comment by wouterken** [comment]
Nice work @ecostanzi! Looks like a good first cut to me. To productionize it there is of course room for some additional logging, error handling etc - the usual suspects - but depending on your use-case that may be overkill!

Just for fun you could probably even take this one step further and deploy it as a wasm module on a Cloudflare worker, to have the conversion run on the edge, to get the converted strings back to your users even faster!
